/** All granular permissions available in the application. */
export const enum Permission {
  ViewDashboard = 'ViewDashboard',
  ManageUsers = 'ManageUsers',
  ManageRoles = 'ManageRoles',
  EditProducts = 'EditProducts',
  ViewProducts = 'ViewProducts',
  ManageSettings = 'ManageSettings',
  ViewAlerts = 'ViewAlerts',
  ManageAlerts = 'ManageAlerts',
  ViewOrders = 'ViewOrders',
  ManageOrders = 'ManageOrders',
  ViewReports = 'ViewReports',
  ManageReports = 'ManageReports',
  ViewCalendar = 'ViewCalendar',
  ManageCalendar = 'ManageCalendar',
  ViewKanban = 'ViewKanban',
  ManageKanban = 'ManageKanban',
  ViewChat = 'ViewChat',
  ViewMaps = 'ViewMaps',
  ViewNotifications = 'ViewNotifications',
  ViewActivityLog = 'ViewActivityLog',
  ViewForms = 'ViewForms',
  ViewComponents = 'ViewComponents',
  ViewMarketplace = 'ViewMarketplace',

  ViewDiagram = 'ViewDiagram',
  AdminAccess = 'AdminAccess',
}
