// Generated by scripts/figma/generate.ts — DO NOT EDIT MANUALLY
// Source: Figma file hTPo6YaE32xCzSFltwxTLQ at 2026-02-19T17:59:52.421Z
// To regenerate: npm run figma:sync

import {
  DEFAULT_ANIMATIONS,
  DEFAULT_BORDER_RADIUS,
  DEFAULT_COMPONENTS_DARK,
  DEFAULT_COMPONENTS_LIGHT,
  DEFAULT_DARK_MODE,
  DEFAULT_LAYOUT,
  DEFAULT_LIGHT_MODE,
  DEFAULT_NEUTRAL,
  DEFAULT_PRIMARY,
  DEFAULT_SECONDARY,
  DEFAULT_SHADOWS,
  DEFAULT_SPACING,
  DEFAULT_STATUS,
  DEFAULT_TRANSITIONS,
  DEFAULT_TYPOGRAPHY,
  DEFAULT_TYPOGRAPHY_COMPONENTS,
} from '../defaults';

import type { ComponentsConfig, ThemeConfig } from '../types';

const FIGMA_COMPONENTS: ComponentsConfig = {
  light: {
    ...DEFAULT_COMPONENTS_LIGHT,
    alertBadges: {
      ...DEFAULT_COMPONENTS_LIGHT.alertBadges,
      error: {
        ...DEFAULT_COMPONENTS_LIGHT.alertBadges.error,
        background: '239 68 68',
        textColor: '255 255 255',
        borderColor: '239 68 68',
      },
      warning: {
        ...DEFAULT_COMPONENTS_LIGHT.alertBadges.warning,
        background: '249 115 22',
        textColor: '255 255 255',
        borderColor: '249 115 22',
      },
      info: {
        ...DEFAULT_COMPONENTS_LIGHT.alertBadges.info,
        background: '254 177 48',
        textColor: '17 19 25',
        borderColor: '254 177 48',
      },
      success: {
        ...DEFAULT_COMPONENTS_LIGHT.alertBadges.success,
        background: '123 164 175',
        textColor: '255 255 255',
        borderColor: '16 185 129',
      },
      outlineFillOpacity: '0.2',
      padding: {
        paddingTop: '8px',
        paddingRight: '5px',
        paddingBottom: '5px',
        paddingLeft: '5px',
      },
      typography: {
        fontFamily: 'Fira Sans Condensed',
        fontSize: '10px',
        fontWeight: '500',
        lineHeight: '15px',
        letterSpacing: '0px',
        textTransform: 'uppercase',
      },
    },
    badges: {
      ...DEFAULT_COMPONENTS_LIGHT.badges,
      error: {
        ...DEFAULT_COMPONENTS_LIGHT.badges.error,
        background: '239 68 68',
        textColor: '17 19 25',
        borderColor: '239 68 68',
      },
      warning: {
        ...DEFAULT_COMPONENTS_LIGHT.badges.warning,
        background: '249 115 22',
        textColor: '17 19 25',
        borderColor: '249 115 22',
      },
      info: {
        ...DEFAULT_COMPONENTS_LIGHT.badges.info,
        background: '254 177 48',
        textColor: '17 19 25',
        borderColor: '254 177 48',
      },
      success: {
        ...DEFAULT_COMPONENTS_LIGHT.badges.success,
        background: '123 164 175',
        textColor: '17 19 25',
        borderColor: '16 185 129',
      },
    },
    menu: { ...DEFAULT_COMPONENTS_LIGHT.menu, background: '250 251 252', textColor: '55 65 81', activeBackground: '0 83 104', borderColor: '229 231 235' },
    textDescription: { ...DEFAULT_COMPONENTS_LIGHT.textDescription, textColor: '59 69 89', fontFamily: 'Fira Sans', fontSize: '12px', fontWeight: '400', lineHeight: '20px', letterSpacing: '2%' },
  },
  dark: {
    ...DEFAULT_COMPONENTS_DARK,
    alertBadges: {
      ...DEFAULT_COMPONENTS_DARK.alertBadges,
      error: {
        ...DEFAULT_COMPONENTS_DARK.alertBadges.error,
        background: '239 68 68',
        textColor: '17 19 25',
        borderColor: '239 68 68',
      },
      warning: {
        ...DEFAULT_COMPONENTS_DARK.alertBadges.warning,
        background: '249 115 22',
        textColor: '17 19 25',
        borderColor: '249 115 22',
      },
      info: {
        ...DEFAULT_COMPONENTS_DARK.alertBadges.info,
        background: '254 177 48',
        textColor: '17 19 25',
        borderColor: '254 177 48',
      },
      success: {
        ...DEFAULT_COMPONENTS_DARK.alertBadges.success,
        background: '123 164 175',
        textColor: '17 19 25',
        borderColor: '16 185 129',
      },
      outlineFillOpacity: '0.2',
      padding: {
        paddingTop: '8px',
        paddingRight: '5px',
        paddingBottom: '5px',
        paddingLeft: '5px',
      },
      typography: {
        fontFamily: 'Fira Sans Condensed',
        fontSize: '10px',
        fontWeight: '500',
        lineHeight: '15px',
        letterSpacing: '0px',
        textTransform: 'uppercase',
      },
    },
    badges: {
      ...DEFAULT_COMPONENTS_DARK.badges,
      error: {
        ...DEFAULT_COMPONENTS_DARK.badges.error,
        background: '239 68 68',
        textColor: '17 19 25',
        borderColor: '239 68 68',
      },
      warning: {
        ...DEFAULT_COMPONENTS_DARK.badges.warning,
        background: '249 115 22',
        textColor: '17 19 25',
        borderColor: '249 115 22',
      },
      info: {
        ...DEFAULT_COMPONENTS_DARK.badges.info,
        background: '254 177 48',
        textColor: '17 19 25',
        borderColor: '254 177 48',
      },
      success: {
        ...DEFAULT_COMPONENTS_DARK.badges.success,
        background: '123 164 175',
        textColor: '17 19 25',
        borderColor: '16 185 129',
      },
    },
    menu: { ...DEFAULT_COMPONENTS_DARK.menu, background: '17 24 39', textColor: '209 213 219', activeBackground: '0 83 104', borderColor: '55 65 81' },
    textDescription: { ...DEFAULT_COMPONENTS_DARK.textDescription, textColor: '180 190 210', fontFamily: 'Fira Sans', fontSize: '12px', fontWeight: '400', lineHeight: '20px', letterSpacing: '2%' },
  },
};

export const FIGMA_DESIGN_THEME: ThemeConfig = {
  id: 'figmaDesign',
  name: 'Figma Design',
  primary: DEFAULT_PRIMARY,
  secondary: DEFAULT_SECONDARY,
  neutral: DEFAULT_NEUTRAL,
  status: DEFAULT_STATUS,
  layout: DEFAULT_LAYOUT,
  spacing: DEFAULT_SPACING,
  borderRadius: DEFAULT_BORDER_RADIUS,
  shadows: DEFAULT_SHADOWS,
  typography: DEFAULT_TYPOGRAPHY,
  transitions: DEFAULT_TRANSITIONS,
  animations: DEFAULT_ANIMATIONS,
  light: DEFAULT_LIGHT_MODE,
  dark: DEFAULT_DARK_MODE,
  components: FIGMA_COMPONENTS,
  typographyComponents: DEFAULT_TYPOGRAPHY_COMPONENTS,
};
