// Generated by scripts/figma/generate.ts — DO NOT EDIT MANUALLY
// Source: Figma file hTPo6YaE32xCzSFltwxTLQ at 2026-02-20T09:47:49.467Z
// To regenerate: npm run figma:sync


import { FIGMA_DESIGN_DARK } from './figmaDesignComponentsDark';
import { FIGMA_DESIGN_LIGHT } from './figmaDesignComponentsLight';

import type { ComponentsConfig } from '../types';

export const FIGMA_DESIGN_COMPONENTS: ComponentsConfig = {
  light: FIGMA_DESIGN_LIGHT,
  dark: FIGMA_DESIGN_DARK,
};
