// Generated by scripts/figma/generate.ts — DO NOT EDIT MANUALLY
// Source: Figma file hTPo6YaE32xCzSFltwxTLQ at 2026-02-18T19:11:00.739Z
// To regenerate: npm run figma:sync

import {
  DEFAULT_ANIMATIONS,
  DEFAULT_BORDER_RADIUS,
  DEFAULT_COMPONENTS_DARK,
  DEFAULT_COMPONENTS_LIGHT,
  DEFAULT_DARK_MODE,
  DEFAULT_LAYOUT,
  DEFAULT_LIGHT_MODE,
  DEFAULT_NEUTRAL,
  DEFAULT_PRIMARY,
  DEFAULT_SECONDARY,
  DEFAULT_SHADOWS,
  DEFAULT_SPACING,
  DEFAULT_STATUS,
  DEFAULT_TRANSITIONS,
  DEFAULT_TYPOGRAPHY,
  DEFAULT_TYPOGRAPHY_COMPONENTS,
} from '../defaults';

import type { ComponentsConfig, ThemeConfig } from '../types';

const FIGMA_COMPONENTS: ComponentsConfig = {
  light: {
    ...DEFAULT_COMPONENTS_LIGHT,
    alertBadges: {
      ...DEFAULT_COMPONENTS_LIGHT.alertBadges,
      error: {
        background: '239 68 68',
        textColor: '255 255 255',
        borderColor: '239 68 68',
      },
      warning: {
        background: '249 115 22',
        textColor: '255 255 255',
        borderColor: '249 115 22',
      },
      info: {
        background: '254 177 48',
        textColor: '17 19 25',
        borderColor: '254 177 48',
      },
      success: {
        background: '123 164 175',
        textColor: '255 255 255',
        borderColor: '16 185 129',
      },
      padding: {
        paddingTop: '7px',
        paddingRight: '5px',
        paddingBottom: '5px',
        paddingLeft: '5px',
      },
      typography: {
        fontFamily: 'Fira Sans Condensed',
        fontSize: '10px',
        fontWeight: '500',
        lineHeight: '15px',
        letterSpacing: '0px',
      },
    },
    badges: {
      ...DEFAULT_COMPONENTS_LIGHT.badges,
      error: {
        background: '239 68 68',
        textColor: '17 19 25',
        borderColor: '239 68 68',
      },
      warning: {
        background: '249 115 22',
        textColor: '17 19 25',
        borderColor: '249 115 22',
      },
      info: {
        background: '254 177 48',
        textColor: '17 19 25',
        borderColor: '254 177 48',
      },
      success: {
        background: '123 164 175',
        textColor: '17 19 25',
        borderColor: '16 185 129',
      },
    },
  },
  dark: {
    ...DEFAULT_COMPONENTS_DARK,
    alertBadges: {
      ...DEFAULT_COMPONENTS_DARK.alertBadges,
      error: {
        background: '239 68 68',
        textColor: '17 19 25',
        borderColor: '239 68 68',
      },
      warning: {
        background: '249 115 22',
        textColor: '17 19 25',
        borderColor: '249 115 22',
      },
      info: {
        background: '254 177 48',
        textColor: '17 19 25',
        borderColor: '254 177 48',
      },
      success: {
        background: '123 164 175',
        textColor: '17 19 25',
        borderColor: '16 185 129',
      },
      padding: {
        paddingTop: '7px',
        paddingRight: '5px',
        paddingBottom: '5px',
        paddingLeft: '5px',
      },
      typography: {
        fontFamily: 'Fira Sans Condensed',
        fontSize: '10px',
        fontWeight: '500',
        lineHeight: '15px',
        letterSpacing: '0px',
      },
    },
    badges: {
      ...DEFAULT_COMPONENTS_DARK.badges,
      error: {
        background: '239 68 68',
        textColor: '17 19 25',
        borderColor: '239 68 68',
      },
      warning: {
        background: '249 115 22',
        textColor: '17 19 25',
        borderColor: '249 115 22',
      },
      info: {
        background: '254 177 48',
        textColor: '17 19 25',
        borderColor: '254 177 48',
      },
      success: {
        background: '123 164 175',
        textColor: '17 19 25',
        borderColor: '16 185 129',
      },
    },
  },
};

export const FIGMA_DESIGN_THEME: ThemeConfig = {
  id: 'figmaDesign',
  name: 'Figma Design',
  primary: DEFAULT_PRIMARY,
  secondary: DEFAULT_SECONDARY,
  neutral: DEFAULT_NEUTRAL,
  status: DEFAULT_STATUS,
  layout: DEFAULT_LAYOUT,
  spacing: DEFAULT_SPACING,
  borderRadius: DEFAULT_BORDER_RADIUS,
  shadows: DEFAULT_SHADOWS,
  typography: DEFAULT_TYPOGRAPHY,
  transitions: DEFAULT_TRANSITIONS,
  animations: DEFAULT_ANIMATIONS,
  light: DEFAULT_LIGHT_MODE,
  dark: DEFAULT_DARK_MODE,
  components: FIGMA_COMPONENTS,
  typographyComponents: DEFAULT_TYPOGRAPHY_COMPONENTS,
};
