// Generated by scripts/figma/generate.ts — DO NOT EDIT MANUALLY
// Source: Figma file hTPo6YaE32xCzSFltwxTLQ at 2026-02-20T09:47:49.467Z
// To regenerate: npm run figma:sync

import {
  DEFAULT_ANIMATIONS,
  DEFAULT_BORDER_RADIUS,
  DEFAULT_DARK_MODE,
  DEFAULT_LAYOUT,
  DEFAULT_LIGHT_MODE,
  DEFAULT_NEUTRAL,
  DEFAULT_PRIMARY,
  DEFAULT_SECONDARY,
  DEFAULT_SHADOWS,
  DEFAULT_SPACING,
  DEFAULT_STATUS,
  DEFAULT_TRANSITIONS,
  DEFAULT_TYPOGRAPHY,
  DEFAULT_TYPOGRAPHY_COMPONENTS,
} from '../defaults';
import { FIGMA_DESIGN_COMPONENTS } from './figmaDesignComponents';

import type { ThemeConfig } from '../types';

export const FIGMA_DESIGN_THEME: ThemeConfig = {
  id: 'figmaDesign',
  name: 'Figma Design',
  primary: DEFAULT_PRIMARY,
  secondary: DEFAULT_SECONDARY,
  neutral: DEFAULT_NEUTRAL,
  status: DEFAULT_STATUS,
  layout: DEFAULT_LAYOUT,
  spacing: DEFAULT_SPACING,
  borderRadius: DEFAULT_BORDER_RADIUS,
  shadows: DEFAULT_SHADOWS,
  typography: DEFAULT_TYPOGRAPHY,
  transitions: DEFAULT_TRANSITIONS,
  animations: DEFAULT_ANIMATIONS,
  light: DEFAULT_LIGHT_MODE,
  dark: DEFAULT_DARK_MODE,
  components: FIGMA_DESIGN_COMPONENTS,
  typographyComponents: DEFAULT_TYPOGRAPHY_COMPONENTS,
};
