// Code generation helpers for producing TypeScript preset files

import type { FigmaExtraction } from './types';

/** Generate the import block and type import for the preset file */
function generateImports(): string[] {
  return [
    '// Generated by scripts/figma/generate.ts — DO NOT EDIT MANUALLY',
    '// To regenerate: npm run figma:sync',
    '',
    'import {',
    '  DEFAULT_ANIMATIONS,',
    '  DEFAULT_BORDER_RADIUS,',
    '  DEFAULT_COMPONENTS,',
    '  DEFAULT_DARK_MODE,',
    '  DEFAULT_LAYOUT,',
    '  DEFAULT_LIGHT_MODE,',
    '  DEFAULT_NEUTRAL,',
    '  DEFAULT_PRIMARY,',
    '  DEFAULT_SECONDARY,',
    '  DEFAULT_SHADOWS,',
    '  DEFAULT_SPACING,',
    '  DEFAULT_STATUS,',
    '  DEFAULT_TRANSITIONS,',
    '  DEFAULT_TYPOGRAPHY,',
    '  DEFAULT_TYPOGRAPHY_COMPONENTS,',
    "} from '../defaults';",
    '',
    "import type { ThemeConfig } from '../types';",
    '',
  ];
}

/** Generate the ThemeConfig export, selecting overridden or default constants */
function generateThemeExport(usedConstants: string[]): string[] {
  const pick = (key: string, figma: string, def: string): string =>
    usedConstants.includes(key) ? figma : def;

  return [
    'export const FIGMA_DESIGN_THEME: ThemeConfig = {',
    "  id: 'figmaDesign',",
    "  name: 'Figma Design',",
    `  primary: ${pick('primary', 'FIGMA_PRIMARY', 'DEFAULT_PRIMARY')},`,
    `  secondary: ${pick('secondary', 'FIGMA_SECONDARY', 'DEFAULT_SECONDARY')},`,
    `  neutral: ${pick('neutral', 'FIGMA_NEUTRAL', 'DEFAULT_NEUTRAL')},`,
    `  status: ${pick('status', 'FIGMA_STATUS', 'DEFAULT_STATUS')},`,
    '  layout: DEFAULT_LAYOUT,',
    '  spacing: DEFAULT_SPACING,',
    '  borderRadius: DEFAULT_BORDER_RADIUS,',
    '  shadows: DEFAULT_SHADOWS,',
    '  typography: DEFAULT_TYPOGRAPHY,',
    '  transitions: DEFAULT_TRANSITIONS,',
    '  animations: DEFAULT_ANIMATIONS,',
    `  light: ${pick('light', 'FIGMA_LIGHT_MODE', 'DEFAULT_LIGHT_MODE')},`,
    `  dark: ${pick('dark', 'FIGMA_DARK_MODE', 'DEFAULT_DARK_MODE')},`,
    '  components: DEFAULT_COMPONENTS,',
    '  typographyComponents: DEFAULT_TYPOGRAPHY_COMPONENTS,',
    '};',
    '',
  ];
}

export function generateScaleOverride(
  constName: string,
  defaultName: string,
  overrideValues: Record<string, unknown> | undefined,
): string[] {
  if (!overrideValues || Object.keys(overrideValues).length === 0) return [];

  const entries = Object.entries(overrideValues)
    .map(([k, v]) => `  '${k}': '${v}'`)
    .join(',\n');

  return [`const ${constName} = {`, `  ...${defaultName},`, entries + ',', '};'];
}

export function generateStatusOverride(
  overrideValues: Record<string, unknown> | undefined,
): string[] {
  if (!overrideValues || Object.keys(overrideValues).length === 0) return [];

  const lines: string[] = ['const FIGMA_STATUS = {', '  ...DEFAULT_STATUS,'];

  for (const [statusKey, statusOverrides] of Object.entries(overrideValues)) {
    if (typeof statusOverrides !== 'object' || !statusOverrides) continue;
    const entries = Object.entries(statusOverrides as Record<string, unknown>)
      .map(([k, v]) => `    '${k}': '${v}'`)
      .join(',\n');
    lines.push(`  ${statusKey}: {`, `    ...DEFAULT_STATUS.${statusKey},`, entries + ',', '  },');
  }

  lines.push('};');
  return lines;
}

export function generateModeOverride(
  constName: string,
  defaultName: string,
  overrideValues: Record<string, unknown> | undefined,
): string[] {
  if (!overrideValues || Object.keys(overrideValues).length === 0) return [];

  const lines: string[] = [`const ${constName} = {`];
  const sections = ['backgrounds', 'text', 'borders'] as const;

  for (const section of sections) {
    const sectionOverrides = overrideValues[section] as Record<string, unknown> | undefined;
    if (sectionOverrides && Object.keys(sectionOverrides).length > 0) {
      const entries = Object.entries(sectionOverrides)
        .map(([k, v]) => `    ${k}: '${v}'`)
        .join(',\n');
      lines.push(`  ${section}: {`, `    ...${defaultName}.${section},`, entries + ',', '  },');
    } else {
      lines.push(`  ${section}: ${defaultName}.${section},`);
    }
  }

  lines.push('};');
  return lines;
}

/** Build section overrides and collect which constants were generated */
function generateOverrideConstants(
  overrides: Record<string, unknown>,
): { lines: string[]; usedConstants: string[] } {
  const lines: string[] = [];
  const usedConstants: string[] = [];

  const generators: [string, () => string[]][] = [
    ['primary', () => generateScaleOverride('FIGMA_PRIMARY', 'DEFAULT_PRIMARY', overrides['primary'] as Record<string, unknown> | undefined)],
    ['secondary', () => generateScaleOverride('FIGMA_SECONDARY', 'DEFAULT_SECONDARY', overrides['secondary'] as Record<string, unknown> | undefined)],
    ['neutral', () => generateScaleOverride('FIGMA_NEUTRAL', 'DEFAULT_NEUTRAL', overrides['neutral'] as Record<string, unknown> | undefined)],
    ['status', () => generateStatusOverride(overrides['status'] as Record<string, unknown> | undefined)],
    ['light', () => generateModeOverride('FIGMA_LIGHT_MODE', 'DEFAULT_LIGHT_MODE', overrides['light'] as Record<string, unknown> | undefined)],
    ['dark', () => generateModeOverride('FIGMA_DARK_MODE', 'DEFAULT_DARK_MODE', overrides['dark'] as Record<string, unknown> | undefined)],
  ];

  for (const [key, generator] of generators) {
    if (overrides[key]) {
      lines.push(...generator(), '');
      usedConstants.push(key);
    }
  }

  return { lines, usedConstants };
}

/** Generate complete TypeScript preset file content */
export function generatePresetCode(
  extraction: FigmaExtraction,
  overrides: Record<string, unknown>,
): string {
  const importLines = generateImports();
  // Add source comment after the first line
  importLines.splice(1, 0, `// Source: Figma file ${extraction.fileKey} at ${extraction.extractedAt}`);

  const { lines: overrideLines, usedConstants } = generateOverrideConstants(overrides);
  const exportLines = generateThemeExport(usedConstants);

  return [...importLines, ...overrideLines, ...exportLines].join('\n');
}
