using System.Text;

namespace MockGenerator;

public static class DtoGenerator
{
    private static readonly HashSet<string> ValueTypes =
        ["int", "long", "float", "double", "decimal", "bool", "DateTime", "DateOnly", "Guid"];

    public static void Generate(
        Dictionary<string, SchemaModel> schemas,
        Dictionary<string, List<string>> enums,
        string ns,
        string outputDir)
    {
        // Generate enums first
        foreach (var (name, values) in enums)
        {
            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("#nullable enable");
            sb.AppendLine($"namespace {ns};");
            sb.AppendLine();
            sb.AppendLine($"public enum {name}");
            sb.AppendLine("{");
            foreach (var value in values)
            {
                sb.AppendLine($"    {value},");
            }
            sb.AppendLine("}");

            var filePath = Path.Combine(outputDir, $"{name}.g.cs");
            File.WriteAllText(filePath, sb.ToString());
            Console.WriteLine($"  Generated enum: {name}.g.cs");
        }

        // Generate DTOs
        foreach (var (name, schema) in schemas)
        {
            if (schema.IsPaginationWrapper)
            {
                GeneratePaginationWrapper(name, schema, ns, outputDir);
                continue;
            }

            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("#nullable enable");
            sb.AppendLine($"namespace {ns};");
            sb.AppendLine();
            sb.AppendLine($"public record {name}");
            sb.AppendLine("{");

            foreach (var prop in schema.Properties)
            {
                var type = FormatType(prop);
                var defaultValue = GetDefaultValue(prop);
                sb.AppendLine($"    public {type} {prop.Name} {{ get; init; }}{defaultValue}");
            }

            sb.AppendLine("}");

            var filePath = Path.Combine(outputDir, $"{name}.g.cs");
            File.WriteAllText(filePath, sb.ToString());
            Console.WriteLine($"  Generated DTO: {name}.g.cs");
        }
    }

    private static void GeneratePaginationWrapper(
        string name, SchemaModel schema, string ns, string outputDir)
    {
        var itemType = schema.PaginationItemType!;

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine($"namespace {ns};");
        sb.AppendLine();
        sb.AppendLine($"public record {name}");
        sb.AppendLine("{");
        sb.AppendLine($"    public List<{itemType}> Items {{ get; init; }} = [];");
        sb.AppendLine("    public int Total { get; init; }");
        sb.AppendLine("    public int Skip { get; init; }");
        sb.AppendLine("    public int Limit { get; init; }");
        sb.AppendLine("}");

        var filePath = Path.Combine(outputDir, $"{name}.g.cs");
        File.WriteAllText(filePath, sb.ToString());
        Console.WriteLine($"  Generated pagination DTO: {name}.g.cs");
    }

    private static string FormatType(PropertyModel prop)
    {
        var type = prop.CSharpType;
        if (prop.IsNullable)
        {
            type += "?";
        }
        return type;
    }

    private static string GetDefaultValue(PropertyModel prop)
    {
        if (prop.IsNullable)
            return "";

        if (prop.IsCollection)
            return " = [];";

        if (prop.CSharpType == "string")
            return " = string.Empty;";

        if (prop.IsReference && !prop.IsEnum && !ValueTypes.Contains(prop.CSharpType))
            return $" = new();";

        return "";
    }
}
