using System.Text;

namespace MockGenerator;

public static class EndpointGenerator
{
    public static void Generate(
        List<EndpointModel> endpoints,
        List<StoreEntity> storeEntities,
        string rootNs,
        string prefix,
        string outputDir)
    {
        var dtoNs = $"{rootNs}.Dtos";
        var endpointNs = $"{rootNs}.Endpoints";
        prefix = prefix.TrimEnd('/');

        // Build a map from base path (without {id} params) to entity DTO name
        // from GET list endpoints that have pagination
        var pathToEntity = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase);
        foreach (var ep in endpoints)
        {
            if (ep is { HttpMethod: "GET", IsPaginatedResponse: true, PaginationItemType: not null })
            {
                pathToEntity[NormalizePath(ep.Path)] = ep.PaginationItemType;
            }
            else if (ep is { HttpMethod: "POST", RequestBodyType: not null })
            {
                var basePath = NormalizePath(ep.Path);
                pathToEntity.TryAdd(basePath, ep.RequestBodyType);
            }
        }

        // Build store entity lookup
        var entityToStoreProp = storeEntities.ToDictionary(e => e.DtoName, e => e.PluralName);

        foreach (var ep in endpoints)
        {
            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("#nullable enable");
            sb.AppendLine("using FastEndpoints;");
            sb.AppendLine($"using {rootNs};");
            sb.AppendLine($"using {dtoNs};");
            sb.AppendLine();
            sb.AppendLine($"namespace {endpointNs};");
            sb.AppendLine();

            var route = BuildRoute(prefix, ep.Path);

            switch (ep.HttpMethod)
            {
                case "GET" when ep.IsPaginatedResponse:
                    GeneratePaginatedListEndpoint(sb, ep, route, entityToStoreProp);
                    break;
                case "GET" when ep.PathParameters.Count > 0:
                    GenerateGetByIdEndpoint(sb, ep, route, pathToEntity, entityToStoreProp);
                    break;
                case "GET":
                    GenerateListEndpoint(sb, ep, route, entityToStoreProp);
                    break;
                case "POST":
                    GenerateCreateEndpoint(sb, ep, route, entityToStoreProp);
                    break;
                case "PUT":
                    GenerateUpdateEndpoint(sb, ep, route, pathToEntity, entityToStoreProp);
                    break;
                case "DELETE":
                    GenerateDeleteEndpoint(sb, ep, route, pathToEntity, entityToStoreProp);
                    break;
                default:
                    Console.WriteLine($"  Skipping unsupported method: {ep.HttpMethod} {ep.Path}");
                    continue;
            }

            var filePath = Path.Combine(outputDir, $"{ep.OperationId}.g.cs");
            File.WriteAllText(filePath, sb.ToString());
            Console.WriteLine($"  Generated Endpoint: {ep.OperationId}.g.cs ({ep.HttpMethod} {route})");
        }
    }

    private static string NormalizePath(string path)
    {
        // Strip path parameters to get base path: /api/customers/{id} -> /api/customers
        var segments = path.Split('/', StringSplitOptions.RemoveEmptyEntries)
            .Where(s => !s.StartsWith('{'));
        return "/" + string.Join("/", segments);
    }

    private static string ResolveEntityType(
        string path,
        Dictionary<string, string> pathToEntity,
        Dictionary<string, string> entityToStoreProp)
    {
        var basePath = NormalizePath(path);
        if (pathToEntity.TryGetValue(basePath, out var entity))
            return entity;

        // Fallback: infer from path segments
        return InferEntityTypeFromPath(path);
    }

    private static string ResolveStoreProp(
        string entityType, Dictionary<string, string> entityToStoreProp)
    {
        if (entityToStoreProp.TryGetValue(entityType, out var prop))
            return prop;

        // Fallback: simple pluralization
        return GetFallbackStorePropName(entityType);
    }

    private static string BuildRoute(string prefix, string path)
    {
        var route = path;
        if (route.StartsWith("/api/", StringComparison.OrdinalIgnoreCase))
            route = route[4..];

        route = System.Text.RegularExpressions.Regex.Replace(
            route, @"\{(\w+)\}",
            m => "{" + SchemaParser.ToPascalCase(m.Groups[1].Value) + "}");

        return prefix + route;
    }

    private static void GeneratePaginatedListEndpoint(
        StringBuilder sb, EndpointModel ep, string route,
        Dictionary<string, string> entityToStoreProp)
    {
        var itemType = ep.PaginationItemType!;
        var responseType = ep.ResponseType!;
        var storeProp = ResolveStoreProp(itemType, entityToStoreProp);

        sb.AppendLine($"public class {ep.OperationId} : Endpoint<{ep.OperationId}Request, {responseType}>");
        sb.AppendLine("{");
        sb.AppendLine("    public override void Configure()");
        sb.AppendLine("    {");
        sb.AppendLine($"        Get(\"{route}\");");
        sb.AppendLine("        AllowAnonymous();");
        sb.AppendLine($"        Tags(\"Generated\", \"{ep.Tag}\");");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine($"    public override async Task HandleAsync({ep.OperationId}Request req, CancellationToken ct)");
        sb.AppendLine("    {");
        sb.AppendLine($"        var all = GeneratedStore.{storeProp};");
        sb.AppendLine("        var items = all.Skip(req.Skip).Take(req.Limit).ToList();");
        sb.AppendLine($"        await SendOkAsync(new {responseType}");
        sb.AppendLine("        {");
        sb.AppendLine("            Items = items,");
        sb.AppendLine("            Total = all.Count,");
        sb.AppendLine("            Skip = req.Skip,");
        sb.AppendLine("            Limit = req.Limit,");
        sb.AppendLine("        }, ct);");
        sb.AppendLine("    }");
        sb.AppendLine("}");
        sb.AppendLine();

        sb.AppendLine($"public record {ep.OperationId}Request");
        sb.AppendLine("{");
        sb.AppendLine("    [QueryParam] public int Skip { get; init; }");
        sb.AppendLine("    [QueryParam] public int Limit { get; init; } = 25;");
        sb.AppendLine("}");
    }

    private static void GenerateListEndpoint(
        StringBuilder sb, EndpointModel ep, string route,
        Dictionary<string, string> entityToStoreProp)
    {
        var responseType = ep.ResponseType ?? "object";
        var storeProp = ResolveStoreProp(responseType, entityToStoreProp);

        sb.AppendLine($"public class {ep.OperationId} : EndpointWithoutRequest<List<{responseType}>>");
        sb.AppendLine("{");
        sb.AppendLine("    public override void Configure()");
        sb.AppendLine("    {");
        sb.AppendLine($"        Get(\"{route}\");");
        sb.AppendLine("        AllowAnonymous();");
        sb.AppendLine($"        Tags(\"Generated\", \"{ep.Tag}\");");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    public override async Task HandleAsync(CancellationToken ct)");
        sb.AppendLine("    {");
        sb.AppendLine($"        await SendOkAsync(GeneratedStore.{storeProp}, ct);");
        sb.AppendLine("    }");
        sb.AppendLine("}");
    }

    private static void GenerateGetByIdEndpoint(
        StringBuilder sb, EndpointModel ep, string route,
        Dictionary<string, string> pathToEntity,
        Dictionary<string, string> entityToStoreProp)
    {
        var responseType = ep.ResponseType ?? "object";
        var entityType = ResolveEntityType(ep.Path, pathToEntity, entityToStoreProp);
        var storeProp = ResolveStoreProp(entityType, entityToStoreProp);
        var idParam = ep.PathParameters.FirstOrDefault();
        var idProp = idParam?.Name ?? "Id";
        var idType = idParam?.CSharpType ?? "int";

        sb.AppendLine($"public class {ep.OperationId} : Endpoint<{ep.OperationId}Request, {responseType}>");
        sb.AppendLine("{");
        sb.AppendLine("    public override void Configure()");
        sb.AppendLine("    {");
        sb.AppendLine($"        Get(\"{route}\");");
        sb.AppendLine("        AllowAnonymous();");
        sb.AppendLine($"        Tags(\"Generated\", \"{ep.Tag}\");");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine($"    public override async Task HandleAsync({ep.OperationId}Request req, CancellationToken ct)");
        sb.AppendLine("    {");
        sb.AppendLine($"        var item = GeneratedStore.{storeProp}.FirstOrDefault(x => x.{idProp} == req.{idProp});");
        sb.AppendLine("        if (item is null) { await SendNotFoundAsync(ct); return; }");
        sb.AppendLine("        await SendOkAsync(item, ct);");
        sb.AppendLine("    }");
        sb.AppendLine("}");
        sb.AppendLine();

        sb.AppendLine($"public record {ep.OperationId}Request");
        sb.AppendLine("{");
        sb.AppendLine($"    public {idType} {idProp} {{ get; init; }}");
        sb.AppendLine("}");
    }

    private static void GenerateCreateEndpoint(
        StringBuilder sb, EndpointModel ep, string route,
        Dictionary<string, string> entityToStoreProp)
    {
        var bodyType = ep.RequestBodyType ?? "object";
        var responseType = ep.ResponseType ?? bodyType;
        var storeProp = ResolveStoreProp(bodyType, entityToStoreProp);
        var getByIdOp = FindGetByIdOperationId(ep);

        sb.AppendLine($"public class {ep.OperationId} : Endpoint<{bodyType}, {responseType}>");
        sb.AppendLine("{");
        sb.AppendLine("    public override void Configure()");
        sb.AppendLine("    {");
        sb.AppendLine($"        Post(\"{route}\");");
        sb.AppendLine("        AllowAnonymous();");
        sb.AppendLine($"        Tags(\"Generated\", \"{ep.Tag}\");");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine($"    public override async Task HandleAsync({bodyType} req, CancellationToken ct)");
        sb.AppendLine("    {");
        sb.AppendLine($"        GeneratedStore.{storeProp}.Add(req);");

        if (getByIdOp is not null)
        {
            sb.AppendLine($"        await SendCreatedAtAsync<{getByIdOp}>(new {{ req.Id }}, req, cancellation: ct);");
        }
        else
        {
            sb.AppendLine("        await SendAsync(req, 201, ct);");
        }

        sb.AppendLine("    }");
        sb.AppendLine("}");
    }

    private static void GenerateUpdateEndpoint(
        StringBuilder sb, EndpointModel ep, string route,
        Dictionary<string, string> pathToEntity,
        Dictionary<string, string> entityToStoreProp)
    {
        var bodyType = ep.RequestBodyType ?? "object";
        var responseType = ep.ResponseType ?? bodyType;
        var entityType = ResolveEntityType(ep.Path, pathToEntity, entityToStoreProp);
        var storeProp = ResolveStoreProp(entityType, entityToStoreProp);

        sb.AppendLine($"public class {ep.OperationId} : Endpoint<{bodyType}, {responseType}>");
        sb.AppendLine("{");
        sb.AppendLine("    public override void Configure()");
        sb.AppendLine("    {");
        sb.AppendLine($"        Put(\"{route}\");");
        sb.AppendLine("        AllowAnonymous();");
        sb.AppendLine($"        Tags(\"Generated\", \"{ep.Tag}\");");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine($"    public override async Task HandleAsync({bodyType} req, CancellationToken ct)");
        sb.AppendLine("    {");
        sb.AppendLine($"        var idx = GeneratedStore.{storeProp}.FindIndex(x => x.Id == req.Id);");
        sb.AppendLine("        if (idx < 0) { await SendNotFoundAsync(ct); return; }");
        sb.AppendLine($"        GeneratedStore.{storeProp}[idx] = req;");
        sb.AppendLine("        await SendOkAsync(req, ct);");
        sb.AppendLine("    }");
        sb.AppendLine("}");
    }

    private static void GenerateDeleteEndpoint(
        StringBuilder sb, EndpointModel ep, string route,
        Dictionary<string, string> pathToEntity,
        Dictionary<string, string> entityToStoreProp)
    {
        var entityType = ResolveEntityType(ep.Path, pathToEntity, entityToStoreProp);
        var storeProp = ResolveStoreProp(entityType, entityToStoreProp);
        var idParam = ep.PathParameters.FirstOrDefault();
        var idProp = idParam?.Name ?? "Id";
        var idType = idParam?.CSharpType ?? "int";

        sb.AppendLine($"public class {ep.OperationId} : Endpoint<{ep.OperationId}Request, EmptyResponse>");
        sb.AppendLine("{");
        sb.AppendLine("    public override void Configure()");
        sb.AppendLine("    {");
        sb.AppendLine($"        Delete(\"{route}\");");
        sb.AppendLine("        AllowAnonymous();");
        sb.AppendLine($"        Tags(\"Generated\", \"{ep.Tag}\");");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine($"    public override async Task HandleAsync({ep.OperationId}Request req, CancellationToken ct)");
        sb.AppendLine("    {");
        sb.AppendLine($"        GeneratedStore.{storeProp}.RemoveAll(x => x.{idProp} == req.{idProp});");
        sb.AppendLine("        await SendNoContentAsync(ct);");
        sb.AppendLine("    }");
        sb.AppendLine("}");
        sb.AppendLine();

        sb.AppendLine($"public record {ep.OperationId}Request");
        sb.AppendLine("{");
        sb.AppendLine($"    public {idType} {idProp} {{ get; init; }}");
        sb.AppendLine("}");
    }

    private static string GetFallbackStorePropName(string typeName)
    {
        if (typeName.EndsWith("y", StringComparison.Ordinal))
            return typeName[..^1] + "ies";
        if (typeName.EndsWith("s", StringComparison.Ordinal))
            return typeName + "es";
        return typeName + "s";
    }

    private static string InferEntityTypeFromPath(string path)
    {
        var segments = path.Split('/', StringSplitOptions.RemoveEmptyEntries)
            .Where(s => !s.StartsWith('{'))
            .ToArray();

        var lastResource = segments.LastOrDefault() ?? "Item";
        var singular = lastResource.EndsWith("ies", StringComparison.OrdinalIgnoreCase)
            ? lastResource[..^3] + "y"
            : lastResource.EndsWith("s", StringComparison.OrdinalIgnoreCase)
                ? lastResource[..^1]
                : lastResource;

        return SchemaParser.ToPascalCase(singular);
    }

    private static string? FindGetByIdOperationId(EndpointModel createEndpoint)
    {
        var entityName = createEndpoint.OperationId.Replace("Create", "");
        return $"Get{entityName}ById";
    }
}
