using System.Text;

namespace MockGenerator;

public static class FakerGenerator
{
    private static readonly HashSet<string> DateTypes = ["DateTime", "DateOnly"];
    private static readonly HashSet<string> NumericTypes = ["int", "long", "float", "double", "decimal"];

    public static void Generate(
        Dictionary<string, SchemaModel> schemas,
        Dictionary<string, List<string>> enums,
        string rootNs,
        string outputDir)
    {
        var dtoNs = $"{rootNs}.Dtos";
        var fakerNs = $"{rootNs}.Fakers";

        foreach (var (name, schema) in schemas)
        {
            if (schema.IsPaginationWrapper)
                continue;

            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("#nullable enable");
            sb.AppendLine("using Bogus;");
            sb.AppendLine($"using {dtoNs};");
            sb.AppendLine();
            sb.AppendLine($"namespace {fakerNs};");
            sb.AppendLine();
            sb.AppendLine($"public sealed class {name}Faker : Faker<{name}>");
            sb.AppendLine("{");
            sb.AppendLine($"    public {name}Faker()");
            sb.AppendLine("    {");

            foreach (var prop in schema.Properties)
            {
                var rule = GetFakerRule(prop, schemas, enums);
                sb.AppendLine($"        RuleFor(x => x.{prop.Name}, {rule});");
            }

            sb.AppendLine("    }");
            sb.AppendLine("}");

            var filePath = Path.Combine(outputDir, $"{name}Faker.g.cs");
            File.WriteAllText(filePath, sb.ToString());
            Console.WriteLine($"  Generated Faker: {name}Faker.g.cs");
        }
    }

    private static string GetFakerRule(
        PropertyModel prop,
        Dictionary<string, SchemaModel> schemas,
        Dictionary<string, List<string>> enums)
    {
        // Handle nullable — use (f, _) => syntax to avoid delegate overload ambiguity
        if (prop.IsNullable)
        {
            var innerRule = GetNonNullableFakerRule(prop, schemas, enums);
            return $"(f, _) => f.Random.Bool(0.8f) ? {ExtractLambdaBody(innerRule)} : default";
        }

        return GetNonNullableFakerRule(prop, schemas, enums);
    }

    private static string GetNonNullableFakerRule(
        PropertyModel prop,
        Dictionary<string, SchemaModel> schemas,
        Dictionary<string, List<string>> enums)
    {
        var name = prop.Name;
        var nameUpper = name.ToUpperInvariant();
        var baseType = prop.CSharpType; // without nullable ?

        // Enum
        if (prop.IsEnum && prop.EnumTypeName is not null && enums.ContainsKey(prop.EnumTypeName))
        {
            return $"f => f.PickRandom<{prop.EnumTypeName}>()";
        }

        // Collection of references — generate nested fakers
        if (prop.IsCollection && prop.ItemType is not null && schemas.ContainsKey(prop.ItemType))
        {
            return $"f => new {prop.ItemType}Faker().Generate(f.Random.Int(1, 5))";
        }

        // Collection of primitives
        if (prop.IsCollection)
        {
            var itemRule = prop.ItemType switch
            {
                "string" => "f.Lorem.Word()",
                "int" => "f.Random.Int(1, 100)",
                _ => "f.Lorem.Word()",
            };
            return $"f => Enumerable.Range(0, f.Random.Int(1, 3)).Select(_ => {itemRule}).ToList()";
        }

        // Nested reference object
        if (prop.IsReference && schemas.ContainsKey(baseType))
        {
            return $"f => new {baseType}Faker().Generate()";
        }

        // Primary ID
        if (name == "Id")
        {
            return baseType switch
            {
                "Guid" => "f => f.Random.Guid()",
                _ => "f => f.IndexFaker + 1",
            };
        }

        // Property-name heuristics (type-aware)
        if (nameUpper.EndsWith("ID") && name != "Id")
            return "f => f.Random.Int(1, 1000)";

        if (nameUpper.Contains("EMAIL") && baseType == "string")
            return "f => f.Internet.Email()";

        if (nameUpper.Contains("PHONE") && baseType == "string")
            return "f => f.Phone.PhoneNumber()";

        if (nameUpper.Contains("FIRSTNAME") && baseType == "string")
            return "f => f.Name.FirstName()";

        if (nameUpper.Contains("LASTNAME") && baseType == "string")
            return "f => f.Name.LastName()";

        if (nameUpper.Contains("NAME") && nameUpper.Contains("COMPANY") && baseType == "string")
            return "f => f.Company.CompanyName()";

        if (nameUpper.Contains("NAME") && baseType == "string")
            return "f => f.Commerce.ProductName()";

        // Date heuristics — BEFORE quantity to avoid "LastRestockedAt" matching "STOCK"
        if (DateTypes.Contains(baseType) && (
            nameUpper.Contains("DATE") || nameUpper.EndsWith("AT") || nameUpper.Contains("TIME")))
        {
            return baseType == "DateOnly"
                ? "f => DateOnly.FromDateTime(f.Date.Recent(90))"
                : "f => f.Date.Recent(90)";
        }

        if (nameUpper.Contains("PRICE") || nameUpper.Contains("AMOUNT") || nameUpper.Contains("COST")
            || nameUpper.Contains("SUBTOTAL") || nameUpper.Contains("TOTAL"))
        {
            return NumericTypes.Contains(baseType) ? "f => f.Finance.Amount(1, 500)" : "f => f.Finance.Amount(1, 500)";
        }

        if (nameUpper.Contains("RATE") && baseType is "double" or "float" or "decimal")
            return "f => Math.Round(f.Random.Double(0, 0.25), 4)";

        if (nameUpper.Contains("DESCRIPTION") && baseType == "string")
            return "f => f.Lorem.Sentence()";

        if ((nameUpper.Contains("URL") || nameUpper.Contains("IMAGE")) && baseType == "string")
            return "f => f.Internet.Url()";

        if ((nameUpper.Contains("ADDRESS") || nameUpper.Contains("STREET")) && baseType == "string")
            return "f => f.Address.StreetAddress()";

        if (nameUpper.Contains("CITY") && baseType == "string")
            return "f => f.Address.City()";

        if (nameUpper.Contains("STATE") && baseType == "string")
            return "f => f.Address.State()";

        if ((nameUpper.Contains("ZIP") || nameUpper.Contains("POSTAL")) && baseType == "string")
            return "f => f.Address.ZipCode()";

        if (nameUpper.Contains("COUNTRY") && baseType == "string")
            return "f => f.Address.Country()";

        if (nameUpper.Contains("SKU") && baseType == "string")
            return "f => f.Commerce.Ean8()";

        if (nameUpper.Contains("CATEGORY") && baseType == "string")
            return "f => f.Commerce.Categories(1)[0]";

        if (nameUpper.Contains("NUMBER") && baseType == "string")
            return "f => f.Random.Replace(\"INV-####-####\")";

        if (nameUpper.Contains("NOTE") && baseType == "string")
            return "f => f.Lorem.Paragraph()";

        if ((nameUpper.Contains("QUANTITY") || nameUpper.Contains("STOCK") || nameUpper.Contains("LEVEL"))
            && NumericTypes.Contains(baseType))
            return "f => f.Random.Int(0, 500)";

        // Type-based fallbacks
        return baseType switch
        {
            "string" => "f => f.Lorem.Word()",
            "int" => "f => f.Random.Int(1, 1000)",
            "long" => "f => f.Random.Long(1, 100000)",
            "float" => "f => f.Random.Float(0, 100)",
            "double" => "f => f.Random.Double(0, 100)",
            "decimal" => "f => f.Finance.Amount()",
            "bool" => "f => f.Random.Bool()",
            "DateTime" => "f => f.Date.Recent(90)",
            "DateOnly" => "f => DateOnly.FromDateTime(f.Date.Recent(90))",
            "Guid" => "f => f.Random.Guid()",
            _ => "f => f.Lorem.Word()",
        };
    }

    private static string ExtractLambdaBody(string rule)
    {
        // "f => f.Something()" -> "f.Something()"
        var arrowIndex = rule.IndexOf("=>", StringComparison.Ordinal);
        return arrowIndex >= 0 ? rule[(arrowIndex + 3)..] : rule;
    }
}
