using System.Text;

namespace MockGenerator;

public static class SeedDataGenerator
{
    public static void Generate(
        Dictionary<string, SchemaModel> schemas,
        List<StoreEntity> storeEntities,
        string rootNs,
        int seedCount,
        string outputDir)
    {
        var dtoNs = $"{rootNs}.Dtos";
        var fakerNs = $"{rootNs}.Fakers";

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine($"using {dtoNs};");
        sb.AppendLine($"using {fakerNs};");
        sb.AppendLine();
        sb.AppendLine($"namespace {rootNs};");
        sb.AppendLine();
        sb.AppendLine("public static class GeneratedStore");
        sb.AppendLine("{");

        foreach (var entity in storeEntities)
        {
            sb.AppendLine($"    public static List<{entity.DtoName}> {entity.PluralName} {{ get; }} = new {entity.DtoName}Faker().Generate({seedCount});");
        }

        sb.AppendLine("}");

        var filePath = Path.Combine(outputDir, "GeneratedStore.g.cs");
        File.WriteAllText(filePath, sb.ToString());
        Console.WriteLine($"  Generated Store: GeneratedStore.g.cs ({storeEntities.Count} entities, {seedCount} items each)");
    }
}
