/** Component showcase and navigation test IDs. */
export const ComponentTestIds = {
  // Grid showcase pages
  SYNCFUSION_GRID_SHOWCASE: 'syncfusion-grid-showcase',
  NATIVE_GRID_SHOWCASE: 'native-grid-showcase',
  NAV_GRID_SYNCFUSION: 'nav-grid-syncfusion',
  NAV_GRID_NATIVE: 'nav-grid-native',
  GRID_SHOWCASE_SECTION: 'grid-showcase-section',
  GRID_ALERT_MANAGEMENT: 'grid-alert-management',
  GRID_ALERT_MANAGEMENT_TABLE: 'grid-alert-management-table',

  // Component Showcase Pages
  NATIVE_BUTTON_SHOWCASE: 'native-button-showcase',
  SYNCFUSION_BUTTON_SHOWCASE: 'syncfusion-button-showcase',
  NATIVE_INPUT_SHOWCASE: 'native-input-showcase',
  SYNCFUSION_INPUT_SHOWCASE: 'syncfusion-input-showcase',
  NATIVE_SELECT_SHOWCASE: 'native-select-showcase',
  SYNCFUSION_SELECT_SHOWCASE: 'syncfusion-select-showcase',
  NATIVE_DATEPICKER_SHOWCASE: 'native-datepicker-showcase',
  SYNCFUSION_DATEPICKER_SHOWCASE: 'syncfusion-datepicker-showcase',
  NATIVE_DIALOG_SHOWCASE: 'native-dialog-showcase',
  SYNCFUSION_DIALOG_SHOWCASE: 'syncfusion-dialog-showcase',
  NATIVE_ALERT_SHOWCASE: 'native-alert-showcase',
  SYNCFUSION_ALERT_SHOWCASE: 'syncfusion-alert-showcase',
  NATIVE_CHECKBOX_SHOWCASE: 'native-checkbox-showcase',
  SYNCFUSION_CHECKBOX_SHOWCASE: 'syncfusion-checkbox-showcase',
  NATIVE_TOAST_SHOWCASE: 'native-toast-showcase',
  SYNCFUSION_TOAST_SHOWCASE: 'syncfusion-toast-showcase',
  NATIVE_TOGGLE_SHOWCASE: 'native-toggle-showcase',
  SYNCFUSION_TOGGLE_SHOWCASE: 'syncfusion-toggle-showcase',
  NATIVE_TOOLBAR_SHOWCASE: 'native-toolbar-showcase',
  SYNCFUSION_TOOLBAR_SHOWCASE: 'syncfusion-toolbar-showcase',
  NATIVE_MENU_SHOWCASE: 'native-menu-showcase',
  SYNCFUSION_MENU_SHOWCASE: 'syncfusion-menu-showcase',
  NATIVE_ACCORDION_SHOWCASE: 'native-accordion-showcase',
  SYNCFUSION_ACCORDION_SHOWCASE: 'syncfusion-accordion-showcase',
  NATIVE_BREADCRUMB_SHOWCASE: 'native-breadcrumb-showcase',
  SYNCFUSION_BREADCRUMB_SHOWCASE: 'syncfusion-breadcrumb-showcase',

  // Syncfusion Accordion Interactive
  SYNCFUSION_ACCORDION_EXPAND_ALL: 'syncfusion-accordion-expand-all',
  SYNCFUSION_ACCORDION_COLLAPSE_ALL: 'syncfusion-accordion-collapse-all',

  // Component Showcase Navigation
  NAV_BUTTON_NATIVE: 'nav-button-native',
  NAV_BUTTON_SYNCFUSION: 'nav-button-syncfusion',
  NAV_INPUT_NATIVE: 'nav-input-native',
  NAV_INPUT_SYNCFUSION: 'nav-input-syncfusion',
  NAV_SELECT_NATIVE: 'nav-select-native',
  NAV_SELECT_SYNCFUSION: 'nav-select-syncfusion',
  NAV_DATEPICKER_NATIVE: 'nav-datepicker-native',
  NAV_DATEPICKER_SYNCFUSION: 'nav-datepicker-syncfusion',
  NAV_DIALOG_NATIVE: 'nav-dialog-native',
  NAV_DIALOG_SYNCFUSION: 'nav-dialog-syncfusion',
  NAV_ALERT_NATIVE: 'nav-alert-native',
  NAV_ALERT_SYNCFUSION: 'nav-alert-syncfusion',
  NAV_CHECKBOX_NATIVE: 'nav-checkbox-native',
  NAV_TOAST_NATIVE: 'nav-toast-native',
  NAV_TOGGLE_NATIVE: 'nav-toggle-native',
  NAV_TOOLBAR_NATIVE: 'nav-toolbar-native',
  NAV_MENU_NATIVE: 'nav-menu-native',
  NAV_ACCORDION_NATIVE: 'nav-accordion-native',
  NAV_BREADCRUMB_NATIVE: 'nav-breadcrumb-native',
  NAV_CHECKBOX_SYNCFUSION: 'nav-checkbox-syncfusion',
  NAV_TOAST_SYNCFUSION: 'nav-toast-syncfusion',
  NAV_TOGGLE_SYNCFUSION: 'nav-toggle-syncfusion',
  NAV_TOOLBAR_SYNCFUSION: 'nav-toolbar-syncfusion',
  NAV_MENU_SYNCFUSION: 'nav-menu-syncfusion',
  NAV_ACCORDION_SYNCFUSION: 'nav-accordion-syncfusion',
  NAV_BREADCRUMB_SYNCFUSION: 'nav-breadcrumb-syncfusion',

  // New component showcase pages
  NATIVE_TABS_SHOWCASE: 'native-tabs-showcase',
  SYNCFUSION_TABS_SHOWCASE: 'syncfusion-tabs-showcase',
  NATIVE_TIMELINE_SHOWCASE: 'native-timeline-showcase',
  SYNCFUSION_TIMELINE_SHOWCASE: 'syncfusion-timeline-showcase',
  NATIVE_TAG_SHOWCASE: 'native-tag-showcase',
  SYNCFUSION_TAG_SHOWCASE: 'syncfusion-tag-showcase',
  NATIVE_BADGE_SHOWCASE: 'native-badge-showcase',
  SYNCFUSION_BADGE_SHOWCASE: 'syncfusion-badge-showcase',
  NATIVE_AVATAR_SHOWCASE: 'native-avatar-showcase',
  SYNCFUSION_AVATAR_SHOWCASE: 'syncfusion-avatar-showcase',
  NATIVE_CARD_SHOWCASE: 'native-card-showcase',
  SYNCFUSION_CARD_SHOWCASE: 'syncfusion-card-showcase',
  NATIVE_PROGRESSBAR_SHOWCASE: 'native-progressbar-showcase',
  SYNCFUSION_PROGRESSBAR_SHOWCASE: 'syncfusion-progressbar-showcase',
  NATIVE_TOOLTIP_SHOWCASE: 'native-tooltip-showcase',
  SYNCFUSION_TOOLTIP_SHOWCASE: 'syncfusion-tooltip-showcase',
  NATIVE_THEMETOGGLE_SHOWCASE: 'native-themetoggle-showcase',

  // New navigation test IDs
  NAV_TABS_NATIVE: 'nav-tabs-native',
  NAV_TABS_SYNCFUSION: 'nav-tabs-syncfusion',
  NAV_TIMELINE_NATIVE: 'nav-timeline-native',
  NAV_TIMELINE_SYNCFUSION: 'nav-timeline-syncfusion',
  NAV_TAG_NATIVE: 'nav-tag-native',
  NAV_TAG_SYNCFUSION: 'nav-tag-syncfusion',
  NAV_BADGE_NATIVE: 'nav-badge-native',
  NAV_BADGE_SYNCFUSION: 'nav-badge-syncfusion',
  NAV_AVATAR_NATIVE: 'nav-avatar-native',
  NAV_AVATAR_SYNCFUSION: 'nav-avatar-syncfusion',
  NAV_CARD_NATIVE: 'nav-card-native',
  NAV_CARD_SYNCFUSION: 'nav-card-syncfusion',
  NAV_PROGRESSBAR_NATIVE: 'nav-progressbar-native',
  NAV_PROGRESSBAR_SYNCFUSION: 'nav-progressbar-syncfusion',
  NAV_TOOLTIP_NATIVE: 'nav-tooltip-native',
  NAV_TOOLTIP_SYNCFUSION: 'nav-tooltip-syncfusion',
  NAV_THEMETOGGLE_NATIVE: 'nav-themetoggle-native',

  // Component SubNavGroup test IDs
  NAV_OVERVIEW_GROUP: 'nav-overview-group',
  NAV_OVERVIEW_GROUP_EXPAND: 'nav-overview-group-expand',
  NAV_ACCORDION_GROUP: 'nav-accordion-group',
  NAV_ACCORDION_GROUP_EXPAND: 'nav-accordion-group-expand',
  NAV_ALERT_GROUP: 'nav-alert-group',
  NAV_ALERT_GROUP_EXPAND: 'nav-alert-group-expand',
  NAV_AVATAR_GROUP: 'nav-avatar-group',
  NAV_AVATAR_GROUP_EXPAND: 'nav-avatar-group-expand',
  NAV_BADGE_GROUP: 'nav-badge-group',
  NAV_BADGE_GROUP_EXPAND: 'nav-badge-group-expand',
  NAV_BREADCRUMB_GROUP: 'nav-breadcrumb-group',
  NAV_BREADCRUMB_GROUP_EXPAND: 'nav-breadcrumb-group-expand',
  NAV_BUTTON_GROUP: 'nav-button-group',
  NAV_BUTTON_GROUP_EXPAND: 'nav-button-group-expand',
  NAV_CARD_GROUP: 'nav-card-group',
  NAV_CARD_GROUP_EXPAND: 'nav-card-group-expand',
  NAV_CHECKBOX_GROUP: 'nav-checkbox-group',
  NAV_CHECKBOX_GROUP_EXPAND: 'nav-checkbox-group-expand',
  NAV_DATEPICKER_GROUP: 'nav-datepicker-group',
  NAV_DATEPICKER_GROUP_EXPAND: 'nav-datepicker-group-expand',
  NAV_DIALOG_GROUP: 'nav-dialog-group',
  NAV_DIALOG_GROUP_EXPAND: 'nav-dialog-group-expand',
  NAV_GRID_GROUP: 'nav-grid-group',
  NAV_GRID_GROUP_EXPAND: 'nav-grid-group-expand',
  NAV_INPUT_GROUP: 'nav-input-group',
  NAV_INPUT_GROUP_EXPAND: 'nav-input-group-expand',
  NAV_MENU_GROUP: 'nav-menu-group',
  NAV_MENU_GROUP_EXPAND: 'nav-menu-group-expand',
  NAV_PROGRESSBAR_GROUP: 'nav-progressbar-group',
  NAV_PROGRESSBAR_GROUP_EXPAND: 'nav-progressbar-group-expand',
  NAV_SELECT_GROUP: 'nav-select-group',
  NAV_SELECT_GROUP_EXPAND: 'nav-select-group-expand',
  NAV_TABS_GROUP: 'nav-tabs-group',
  NAV_TABS_GROUP_EXPAND: 'nav-tabs-group-expand',
  NAV_TAG_GROUP: 'nav-tag-group',
  NAV_TAG_GROUP_EXPAND: 'nav-tag-group-expand',
  NAV_TIMELINE_GROUP: 'nav-timeline-group',
  NAV_TIMELINE_GROUP_EXPAND: 'nav-timeline-group-expand',
  NAV_TOAST_GROUP: 'nav-toast-group',
  NAV_TOAST_GROUP_EXPAND: 'nav-toast-group-expand',
  NAV_TOGGLE_GROUP: 'nav-toggle-group',
  NAV_TOGGLE_GROUP_EXPAND: 'nav-toggle-group-expand',
  NAV_TOOLBAR_GROUP: 'nav-toolbar-group',
  NAV_TOOLBAR_GROUP_EXPAND: 'nav-toolbar-group-expand',
  NAV_TOOLTIP_GROUP: 'nav-tooltip-group',
  NAV_TOOLTIP_GROUP_EXPAND: 'nav-tooltip-group-expand',
} as const;
