/** Sidebar navigation test IDs — extracted to keep testIds.ts under the line limit. */
export const SidebarTestIds = {
  // Org Switcher
  ORG_SWITCHER: 'org-switcher',
  ORG_SWITCHER_MENU: 'org-switcher-menu',
  ORG_SWITCHER_ITEM: 'org-switcher-item',
  ORG_AVATAR: 'org-avatar',
  ORG_BADGE: 'org-badge',

  // Sidebar Navigation (ThemeStudio)
  SIDEBAR_SEARCH: 'sidebar-search',
  SIDEBAR_BACK_MAIN: 'sidebar-back-main',
  NAV_SAMPLE_MANAGER: 'nav-sample-manager',
  NAV_ALERTS_INCIDENTS: 'nav-alerts-incidents',
  NAV_ALERTS_INCIDENTS_EXPAND: 'nav-alerts-incidents-expand',
  NAV_ALERTS_MGMT: 'nav-alerts-mgmt',
  NAV_INCIDENTS_MGMT: 'nav-incidents-mgmt',
  NAV_NOTIFICATIONS: 'nav-notifications',
  NAV_ACTIVITY_LOG: 'nav-activity-log',
  NAV_USER_PROFILE: 'nav-user-profile',
  NAV_ADMIN_HUB: 'nav-admin-hub',
  NAV_MARKETPLACE: 'nav-marketplace',
  NAV_ADMIN_MANAGEMENT: 'nav-admin-management',
  NAV_ADMIN_MANAGEMENT_EXPAND: 'nav-admin-management-expand',
  NAV_ADMIN_USER_MGMT: 'nav-admin-user-mgmt',
  NAV_ADMIN_ROLE_MGMT: 'nav-admin-role-mgmt',
  NAV_ADMIN_CONFIG: 'nav-admin-config',
  NAV_ADMIN_CONFIG_EXPAND: 'nav-admin-config-expand',
  NAV_ADMIN_THEME: 'nav-admin-theme',
  NAV_ADMIN_SYSTEM: 'nav-admin-system',
  NAV_ADMIN_MARKETPLACE: 'nav-admin-marketplace',
  NAV_ADMIN_MARKETPLACE_EXPAND: 'nav-admin-marketplace-expand',
  NAV_ADMIN_INTEGRATIONS: 'nav-admin-integrations',
  NAV_ADMIN_PLUGINS: 'nav-admin-plugins',
  NAV_ADMIN_RESOURCES: 'nav-admin-resources',
  NAV_ADMIN_RESOURCES_EXPAND: 'nav-admin-resources-expand',
  NAV_ADMIN_DOCS: 'nav-admin-docs',
  NAV_ADMIN_SUPPORT: 'nav-admin-support',

  // Sidebar Sub-menus
  NAV_PRODUCTS_NATIVE: 'nav-products-native',
  NAV_PRODUCTS_SYNCFUSION: 'nav-products-syncfusion',
  NAV_PRODUCTS_EXPAND: 'nav-products-expand',
  NAV_COMPONENTS_NATIVE: 'nav-components-native',
  NAV_COMPONENTS_SYNCFUSION: 'nav-components-syncfusion',
  NAV_COMPONENTS_EXPAND: 'nav-components-expand',
  NAV_COMPONENTS_SYNCFUSION_EXPAND: 'nav-components-syncfusion-expand',
  NAV_COMPONENTS_NATIVE_EXPAND: 'nav-components-native-expand',
  NAV_FORMS: 'nav-forms',
  NAV_FORMS_EXPAND: 'nav-forms-expand',
  NAV_FORMS_SYNCFUSION: 'nav-forms-syncfusion',
  NAV_FORMS_NATIVE: 'nav-forms-native',
} as const;
