import axios, { type AxiosRequestConfig, type AxiosResponse, type RawAxiosResponseHeaders } from 'axios';

const DUMMYJSON_BASE_URL = 'https://dummyjson.com';

const axiosInstance = axios.create({
  baseURL: DUMMYJSON_BASE_URL,
  headers: {
    'Content-Type': 'application/json',
  },
});

/**
 * Convert axios headers to web-standard Headers object
 */
function convertHeaders(axiosHeaders: RawAxiosResponseHeaders): Headers {
  const headers = new Headers();
  Object.entries(axiosHeaders).forEach(([key, value]) => {
    if (typeof value === 'string') headers.append(key, value);
  });
  return headers;
}

/**
 * Orval 8.x compatible mutator - accepts URL and optional RequestInit
 * The return type T is the full response shape including { data, status, headers }
 * as generated by orval 8.x, so we construct that shape here
 */
export const apiInstance = async <T>(
  url: string,
  options?: RequestInit,
): Promise<T> => {
  const method = options?.method ?? 'GET';
  const headersRecord: Record<string, string> = {};

  if (options?.headers instanceof Headers)
    options.headers.forEach((value, key) => {
      headersRecord[key] = value;
    });
  else if (options?.headers) Object.assign(headersRecord, options.headers);

  // Build config object, only include signal if it exists
  const config: AxiosRequestConfig = {
    url,
    method,
    headers: headersRecord,
    data: options?.body,
  };

  // Only add signal if defined (axios GenericAbortSignal type)
  if (options?.signal) config.signal = options.signal;

  const response: AxiosResponse<unknown> = await axiosInstance(config);

  // Orval 8.x expects { data: actualData, status: number, headers: Headers }
  const result: unknown = {
    data: response.data,
    status: response.status,
    headers: convertHeaders(response.headers),
  };

  // Safe type assertion since orval expects the exact response shape
  // eslint-disable-next-line @typescript-eslint/consistent-type-assertions
  return result as T;
};

export default apiInstance;
