/** Icon name identifiers for sidebar navigation items. */
export const enum IconName {
  Dashboard = 'dashboard',
  Folder = 'folder',
  User = 'user',
  Activity = 'activity',
  ShieldAlert = 'shieldAlert',
  Bell = 'bell',
  Globe = 'globe',
  Zap = 'zap',
  Signal = 'signal',
  ShieldCheck = 'shieldCheck',
  BarChart = 'barChart',
  Cog = 'cog',
  Settings = 'settings',
  Store = 'store',
  Key = 'key',
  Wrench = 'wrench',
  Palette = 'palette',
  Filter = 'filter',
  Refresh = 'refresh',
  Download = 'download',
  MoreVertical = 'moreVertical',
  Layout = 'layout',
  MessageSquare = 'messageSquare',
  PieChart = 'pieChart',
  FormInput = 'formInput',
}
