/**
 * Maps IconName enum values to icon components.
 */
import {
  IconDashboard,
  IconFolder,
  IconUser,
  IconActivity,
  IconShieldAlert,
  IconBell,
  IconGlobe,
  IconZap,
  IconSignal,
  IconShieldCheck,
  IconBarChart,
  IconCog,
  IconSettings,
  IconStore,
  IconKey,
  IconWrench,
  IconPalette,
  IconFilter,
  IconRefresh,
  IconDownload,
  IconMoreVertical,
  IconLayout,
  IconMessageSquare,
  IconPieChart,
  IconFormInput,
  IconSliders,
  IconChartBar,
  IconTrendingUp,
  IconTarget,
  IconEye,
  IconShield,
  IconBook,
  IconUsers,
  IconMonitor,
  IconLock,
  IconList,
  IconClipboard,
  IconBriefcase,
  IconFileText,
  IconPackage,
  IconCalendar,
  IconEdit,
  IconMapPin,
  IconMessageCircle,
} from '@/components/icons';

import { IconName } from './iconName';

type IconComponent = (props: { className?: string }) => JSX.Element;

const ICON_MAP: Record<IconName, IconComponent> = {
  [IconName.Dashboard]: IconDashboard,
  [IconName.Folder]: IconFolder,
  [IconName.User]: IconUser,
  [IconName.Activity]: IconActivity,
  [IconName.ShieldAlert]: IconShieldAlert,
  [IconName.Bell]: IconBell,
  [IconName.Globe]: IconGlobe,
  [IconName.Zap]: IconZap,
  [IconName.Signal]: IconSignal,
  [IconName.ShieldCheck]: IconShieldCheck,
  [IconName.BarChart]: IconBarChart,
  [IconName.Cog]: IconCog,
  [IconName.Settings]: IconSettings,
  [IconName.Store]: IconStore,
  [IconName.Key]: IconKey,
  [IconName.Wrench]: IconWrench,
  [IconName.Palette]: IconPalette,
  [IconName.Filter]: IconFilter,
  [IconName.Refresh]: IconRefresh,
  [IconName.Download]: IconDownload,
  [IconName.MoreVertical]: IconMoreVertical,
  [IconName.Layout]: IconLayout,
  [IconName.MessageSquare]: IconMessageSquare,
  [IconName.PieChart]: IconPieChart,
  [IconName.FormInput]: IconFormInput,
  [IconName.Sliders]: IconSliders,
  [IconName.ChartBar]: IconChartBar,
  [IconName.TrendingUp]: IconTrendingUp,
  [IconName.Target]: IconTarget,
  [IconName.Eye]: IconEye,
  [IconName.Shield]: IconShield,
  [IconName.Book]: IconBook,
  [IconName.Users]: IconUsers,
  [IconName.Monitor]: IconMonitor,
  [IconName.Lock]: IconLock,
  [IconName.List]: IconList,
  [IconName.Clipboard]: IconClipboard,
  [IconName.Briefcase]: IconBriefcase,
  [IconName.FileText]: IconFileText,
  [IconName.Package]: IconPackage,
  [IconName.Calendar]: IconCalendar,
  [IconName.Kanban]: IconClipboard,
  [IconName.Gantt]: IconBarChart,
  [IconName.Edit]: IconEdit,
  [IconName.FolderOpen]: IconFolder,
  [IconName.MessageCircle]: IconMessageCircle,
  [IconName.FileSearch]: IconFileText,
  [IconName.Table]: IconLayout,
  [IconName.MapPin]: IconMapPin,
  [IconName.GitBranch]: IconActivity,
};

export function getIcon(name: IconName): IconComponent {
  return ICON_MAP[name];
}
