// Path prefixes used for sidebar active-state matching

export const enum RoutePrefix {
  DashboardHome = '/dashboard/home',
  Components = '/components',
  ComponentsButton = '/components/button',
  ComponentsCheckbox = '/components/checkbox',
  ComponentsGrid = '/components/grid',
  ComponentsInput = '/components/input',
  ComponentsSelect = '/components/select',
  ComponentsTabs = '/components/tabs',
  ComponentsBreadcrumb = '/components/breadcrumb',
  ComponentsMenu = '/components/menu',
  ComponentsToolbar = '/components/toolbar',
  ComponentsAccordion = '/components/accordion',
  ComponentsToast = '/components/toast',
  ComponentsDialog = '/components/dialog',
  ComponentsAlert = '/components/alert',
  ComponentsTooltip = '/components/tooltip',
  ComponentsCard = '/components/card',
  ComponentsBadge = '/components/badge',
  ComponentsAvatar = '/components/avatar',
  ComponentsTag = '/components/tag',
  ComponentsLoader = '/components/loader',
  ComponentsSlider = '/components/slider',
  ComponentsPillBadge = '/components/pillbadge',
  ComponentsProgressBar = '/components/progressbar',
  ComponentsTimeline = '/components/timeline',
  ComponentsDatePicker = '/components/datepicker',
  ComponentsToggle = '/components/toggle',
  ComponentsColors = '/components/colors',
  ComponentsIcons = '/components/icons',
  ComponentsThemeToggle = '/components/themetoggle',
  AlertsIncidents = '/alerts-incidents',
  Forms = '/forms',
  Products = '/products',
  Notifications = '/notifications',
  UserProfile = '/profile',
  ActivityLog = '/activity-log',
  Customers = '/customers',
  Invoices = '/invoices',
  Orders = '/orders',
  Inventory = '/inventory',
  Settings = '/settings',
  Calendar = '/calendar',
  Kanban = '/kanban',
}
