// Path prefixes used for sidebar active-state matching

export const enum RoutePrefix {
  Components = '/dashboard/components',
  ComponentsButton = '/dashboard/components/button',
  ComponentsCheckbox = '/dashboard/components/checkbox',
  ComponentsGrid = '/dashboard/components/grid',
  ComponentsInput = '/dashboard/components/input',
  ComponentsSelect = '/dashboard/components/select',
  ComponentsTabs = '/dashboard/components/tabs',
  ComponentsBreadcrumb = '/dashboard/components/breadcrumb',
  ComponentsMenu = '/dashboard/components/menu',
  ComponentsToolbar = '/dashboard/components/toolbar',
  ComponentsAccordion = '/dashboard/components/accordion',
  ComponentsToast = '/dashboard/components/toast',
  ComponentsDialog = '/dashboard/components/dialog',
  ComponentsAlert = '/dashboard/components/alert',
  ComponentsTooltip = '/dashboard/components/tooltip',
  ComponentsCard = '/dashboard/components/card',
  ComponentsBadge = '/dashboard/components/badge',
  ComponentsAvatar = '/dashboard/components/avatar',
  ComponentsTag = '/dashboard/components/tag',
  ComponentsProgressBar = '/dashboard/components/progressbar',
  ComponentsTimeline = '/dashboard/components/timeline',
  ComponentsDatePicker = '/dashboard/components/datepicker',
  ComponentsToggle = '/dashboard/components/toggle',
  ComponentsThemeToggle = '/dashboard/components/themetoggle',
  Forms = '/dashboard/forms',
  Products = '/dashboard/products',
}
