// Theme store types - re-export from types folder
// This file maintains backward compatibility with existing imports

export type {
  // Color types
  Mode,
  ColorScale,
  StatusColor,
  StatusColors,
  StatusKey,
  StatusShade,
  ColorShade,
  BackgroundColors,
  TextColors,
  BorderColors,
  ThemeModeConfig,
  ThemeModeConfigUpdate,
  // Layout types
  LayoutConfig,
  BorderRadiusConfig,
  TypographyConfig,
  TransitionConfig,
  SpacingConfig,
  ShadowConfig,
  // Component types
  ShadowScale,
  HeaderComponentConfig,
  SidebarComponentConfig,
  ButtonStateColors,
  ButtonVariant,
  ButtonsComponentConfig,
  InputsConfig,
  DataGridConfig,
  CardsConfig,
  ModalsConfig,
  BadgeVariant,
  BadgesConfig,
  SelectConfig,
  DatePickerConfig,
  DialogConfig,
  FlexDirection,
  FlexWrap,
  FlexJustify,
  FlexAlign,
  FlexBoxConfig,
  ErrorAnimationType,
  ErrorMessagesConfig,
  AlertVariantConfig,
  AlertsConfig,
  ToastConfig,
  MessageConfig,
  ComponentConfigSingle,
  ComponentsConfig,
  // Theme types
  ThemeConfig,
  ThemeState,
} from './types/index';
